# Generated by Django 6.0 on 2025-12-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('verified', 'Verified'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
