# Generated by Django 6.0 on 2025-12-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroEcommerce', '0002_alter_farmer_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
