# Generated by Django 6.0 on 2025-12-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroEcommerce', '0003_alter_farmer_is_active_alter_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='vendor/qr/'),
        ),
    ]
